### ISSUE TITLE
Declaration of Symfony\Component\Console\Style\OutputStyle::write() is incompatible

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#159]
Composer v2.0.10 is bundled with symfony/console where declaration of `Symfony\Component\Console\Style\OutputStyle` is

```php
public function write($messages, $newline = false, $type = self::OUTPUT_NORMAL)
```

while in my app is

```php
public function write($messages, bool $newline = false, int $type = self::OUTPUT_NORMAL)
```

It somehow causes `composer unused` to crash

```
Reading ./composer.json (/Users/user/project/composer.json)
Loading config file /Users/user/.composer/auth.json
Loading config file ./composer.json (/Users/user/project/composer.json)
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/user/project): git branch -a --no-color --no-abbrev -v
Executing command (/Users/user/project): git rev-list master..composer
Executing command (/Users/user/project): git rev-list remotes/origin/master..composer
Reading /Users/user/.composer/composer.json
Loading config file /Users/user/.composer/auth.json
Loading config file /Users/user/.composer/composer.json (/Users/user/.composer/composer.json)
Loading config file /Users/user/.composer/auth.json
Reading /Users/user/.composer/auth.json
Reading /Users/user/project/vendor/composer/installed.json
Loading plugin Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin
Loading plugin PHPStan\ExtensionInstaller\Plugin
Loading plugin Roave\YouAreUsingItWrong\Hook
Loading plugin Icanhazstring\Composer\Unused\UnusedPlugin
Running 2.0.10 (2021-02-23 16:11:37) with PHP 7.4.15 on Darwin / 20.3.0
PHP Fatal error:  Declaration of Symfony\Component\Console\Style\OutputStyle::write($messages, bool $newline = false, int $type = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $options = 0) in /Users/user/project/vendor/symfony/console/Style/OutputStyle.php on line 52
```

**Comment by icanhazstring** [comment]
Hi. What version of `symfony/console` do you have installed?

**Comment by simPod** [comment]
Sorry, it's 5.2.3. I require it directly in my app.

```
me/project                      dev-master  requires  symfony/console (^v5.2.3)
cdn77/tracy-blue-screen-bundle  v0.0.1      requires  symfony/console (^5.0)
composer/composer               2.0.10      requires  symfony/console (^2.8.52 || ^3.4.35 || ^4.4 || ^5.0)
doctrine/doctrine-bundle        2.2.3       requires  symfony/console (^3.4.30|^4.3.3|^5.0)
doctrine/orm                    2.8.1       requires  symfony/console (^3.0|^4.0|^5.0)
sentry/sentry-symfony           4.0.1       requires  symfony/console (^3.4.43||^4.4.11||^5.0.11)
simpod/kafka-bundle             v0.5.0      requires  symfony/console (^5.0)
vimeo/psalm                     4.4.1       requires  symfony/console (^3.4.17 || ^4.1.6 || ^5.0)
```

**Comment by icanhazstring** [comment]
Ok thanks. Let me check what I can do about it :)

**Comment by icanhazstring** [comment]
Do you have any other plugins installed which may cause this problem?
Because `composer-unused` is not directly dependent on `symfony/console`.

I have found a similar issue to yours here:
https://github.com/symfony/symfony/issues/39368

Where they point out a plugin, but as I said. A direct dependency to `symfony/console` is not present.
Can you check for another plugin that maybe has a dependency to it?

**Comment by simPod** [comment]
Only those I listed here though `-vvv`.  I believe it might be cause by `unused` loading `composer/composer` `vendor` folder but that's a bit wild guess for now.

**Comment by naderman** [comment]
@icanhazstring I somewhat suspect the problem is that you have a require on composer in your plugin (why? it's a plugin, why do you need every project to then also install copy of composer as a dependency?) So composer will create an autoloader for your plugin with all the dependencies of your plugin, which requires composer which requires symfony/console. @seldaek do you think it's possible the 2.0.10 change made it so this autoloader now covers the one used in Composer, so the plugin gets the project's console instead of composer's?

**Comment by icanhazstring** [comment]
I do have the requirements as I need to parse and load every dependency of a project this plugin is required in.

I took it as a shortcut to load every package and find the require statements to see what package is used by another package.

Also the autoload information is crucial to parse the source files for provided symbols.

**Comment by naderman** [comment]
I'm not sure I understand why any of that means you have to put "composer/composer" in the require section of your plugin?

**Comment by Seldaek** [comment]
> @Seldaek do you think it's possible the 2.0.10 change made it so this autoloader now covers the one used in Composer, so the plugin gets the project's console instead of composer's?

Yes this was specifically the intent, that the project-installed versions now take priority over the composer.phar-bundled versions. Because Composer is typically compatible with the whole range of symfony components we support, but project-files/script handlers/plugins may not be.

I assume what happened here is that this plugin depended on the fact that previously bundled symfony packages were stuck at 2.8, and so it's now not compatible with latest symfony deps.

**Comment by Seldaek** [comment]
Ah no sorry re-reading the OP, I guess the problem is we load part of the symfony/console classes in v2.8.x when initializing Composer, then create the project autoloader for the plugin and from that point on symfony/console 5.2.3 files get loaded, and those two don't mix well together. Not sure if we should undo the autoload change or rather preload all classes Composer relies on so that we enforce these are consistent between each other (which sounds like maybe a pita to impl)?

**Comment by lukasbestle** [comment]
Could this be solved by making Composer a dev-dependency? During runtime as a Composer plugin, the plugin has access to the Composer classes anyway.

**Comment by icanhazstring** [comment]
> Could this be solved by making Composer a dev-dependency? During runtime as a Composer plugin, the plugin has access to the Composer classes anyway.

Is that so? I didn't know. That is why I have it as a hard requirement. I will try.

Anyway, the problem @Seldaek mentioned seems important 😉

**Comment by Seldaek** [comment]
Ok Composer 2.0.11 is out and reverts the change entirely so hopefully that fixes things.

**Comment by simPod** [comment]
I can confirm the issue is fixed. Thanks!

**Comment by Seldaek** [comment]
Great. That said, yes @icanhazstring I'd imagine `composer/composer` should only be in require-dev so you can run your test suite. At runtime the require on `composer-plugin-api` should be enough?

**Comment by icanhazstring** [comment]
I will try @Seldaek. And thanks for the fix 🙏

**Comment by icanhazstring** [comment]
> I will try @Seldaek. And thanks for the fix 🙏

Not that easy tho. I need to change my phar boxing so that composer/composer is present if I create the phar file. Otherwise the sources are not there. But yeah, I should change this in the future. 👍

**Comment by icanhazstring** [comment]
@simPod this issue is solved then?
I will open a new one for myself to remove `composer/composer` from `require`

**Comment by simPod** [comment]
@icanhazstring yes. `unused` is up and running in CI again 🚀
