### ISSUE TITLE
bin/composer-unused not working when composer/composer not present

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#250]
## Describe the bug
Currently `composer/composer` is used to "fake" a composer executable using the `bin/composer-unused` binary.
This is not possible anymore as the dependency to it was moved to dev to avoid conflicting while installing the tool.

The binary should be removed altogether an only bundled with the phar archive where `composer/composer` is shipped with.
If installed as plugin `composer unused` should be the way to go.

**Comment by icanhazstring** [comment]
Will probably try to introduce a backward compatible change to the binary to avoid releasing 0.8 only for that.
This will check if the needed classes for the binary are present when executing it. Maybe I can fall back to using `composer unused` using symfony/process then.

**Comment by icanhazstring** [comment]
@AndreasA already working on a backward compatible fix right now.
In the future I will try and change something up, will probably remove the tight coupling with composer, and provide a separate plugin which integrates composer-unused as a composer plugin.

See #251

**Comment by AndreasA** [comment]
@icanhazstring Ok. so a separate binary will still be available in the future too?

**Comment by icanhazstring** [comment]
Yes, probably going to integrate symfony/console directly, and adding a new command into composer/console

**Comment by icanhazstring** [comment]
@AndreasA as you are using `bin/composer-unused` can you validate the change I made in #251 ?

**Comment by AndreasA** [comment]
@icanhazstring During installation with composer, if I switch to the fix branch in the require section, I get `bin/composer-unused` file not found in package. Not really sure why though

**Comment by AndreasA** [comment]
@icanhazstring  OK. If I switched the preferred-install to src for the package it worked, maybe the file is ignored in gitattributes or similar?

however, I get a TypeError that the first argument of symfony process must be an array but a string is given. Maybe you want to use `fromShellCommandline` instead? I think it depends on which version of symfony/process is used though.

**Comment by AndreasA** [comment]
@icanhazstring OK. If I use `fromShellCommandline` it goes one step further but in combination with the composer bin plugin it will fail as `Command "unused" is not defined.` is returned then. As the unused command/plugin is only registered in the vendor-bin namespaced `composer.json`. 

This can be bypassed by starting it from the corresponding subdirectory but then the wrong directory / composer.json is analyzed regarding unused dependencies.

**Comment by icanhazstring** [comment]
Not as easy tho.
Can you give me a clue about the project setup you are trying to run this tool against?

**Comment by AndreasA** [comment]
Well there is basically:
- composer.json --> root project one
    - contains the bin plugin: https://github.com/bamarni/composer-bin-plugin
- vendor-bin/composer-unused/composer.json --> composer.json for unused dependency check added using composer bin plugin with the `composer-unused` namespace.
- src/ --> contains sources defined in the root composer.json autoload
- bin/vendor/composer-unused --> link created for composer unused binary by the bin plugin.

Now I want to run the command `bin/vendor/composer-unused` against the root project composer.json and the src directory.

maybe also a bug in composer bin plugin because the unused plugin is not available through the composer bin plugin namespace. 

It was working fine with `0.7.9`. I guess it also might work, if I add `composer/composer` as dependency to the `vendor-bin/composer-unused/composer.json`.

I think the only permanent solution would be to make the unused plugin available as symfony console command or similar, instead of a plugin at all.

**Comment by icanhazstring** [comment]
Thanks for your feedback.
I have released a 0.7.11 which reverts previous changes.

This issue will stay open as information for 0.8 to remove the dependency to `composer/composer`alltogether.

**Comment by icanhazstring** [comment]
Starting with 0.8 the requirement to `composer/composer` is removed.
As mentioned here (already fixed in PR) #252
