### ISSUE TITLE
setAdditionalFilesFor not working (or maybe I didn't understand)

### ISSUE THREAD

**Issue by mmenozzi** [composer-unused/composer-unused#329]
## Describe the bug

[Here](https://github.com/mmenozzi/Sylius-Standard/commit/acd54bcca41c0b4a3f0d665aa27cd80e63912e03) I'm trying to introduce `composer-unused` on [Sylius/Sylius-Standard](https://github.com/Sylius/Sylius-Standard). There are dependencies like `sylius/paypal-plugin` or `symfony/dotenv` that are not used in `src/` but in  `config/bundles.php` or `config/bootstrap.php` files. So I configured those files for those dependencies [here](https://github.com/mmenozzi/Sylius-Standard/blob/composer-unused/composer-unused.php).

But [it does not work](https://github.com/mmenozzi/Sylius-Standard/runs/5349419143?check_suite_focus=true#step:16:1).

Is this a bug or I didn't get how it should work?

**Comment by icanhazstring** [comment]
Hi. Thanks for asking. If those packages are "used" in paths outside your projects autoload you need to configure those additional paths for your project.

So the correct way would be to add an array of those two files with your projects name.

This way these files will be scanned in addition to your autoload configuration.

**Comment by mmenozzi** [comment]
Hi @icanhazstring, thank you for your quick reply.

Do you mean that I should add those config/bundles.php and config/bootstrap.php files to the autoload.files section of the composer.json?

If this is the case, what is the reason for the setAddidionalFilesFor in the configuration?

**Comment by icanhazstring** [comment]
You can use it the same way I did with composer-unused here:

 ```
 ->​setAdditionalFilesFor​('icanhazstring/composer-unused'​, [...]);
```

Use your projects name from `composer.json` to add additional places to scan.

The disadvantage is using composer autoload for libraries or even projects is that you don't want those files to be autoloader all the time.

Also some libraries do this on purpose because the will change some behavior of existing functions. So the consumer has to decide where to use these. But then again, composer-unused is based on autoload first, because this is the default behavior for the majority of packages. So for the you the consumer of those package you can define additional places to look for provided or consumed symbols for composer-unused to pick up.

**Comment by mmenozzi** [comment]
So I have to use sylius/sylius-standard instead of sylius/paypal-plugin and symfony/dotenv in my configuration?

**Comment by icanhazstring** [comment]
Yes. And you have to combine both files into a one `setAdditionalFiles` call.

**Comment by mmenozzi** [comment]
Yes now [it](https://github.com/Sylius/Sylius-Standard/runs/5351262256?check_suite_focus=true#step:16:1) works! Thank you very much!

**Comment by icanhazstring** [comment]
Nice 🙂
BTW the `-o github` is not really necessary as the implementation will autodetect github CI to change output.

**Comment by mmenozzi** [comment]
Ah ok thank you!
