### ISSUE TITLE
Missing PHAR from 0.8.6 release

### ISSUE THREAD

**Issue by DAcodedBEAT** [composer-unused/composer-unused#444]
## Describe the bug

`curl -OL https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar` (as provided from the README) returned a file with the contents `Not Found`.

When looking at https://github.com/composer-unused/composer-unused/releases/tag/0.8.6 , it looks like the PHAR is not part of the provided release assets, like it was in previous releases.

May we please have the `composer-unused.phar` and `composer-unused.phar.asc` release assets for release 0.8.6?

## Additional information
If you encounter environment problems, such as memory limit, provide some information
about your `php -i`

N/A

**Comment by icanhazstring** [comment]
Yep I know. Currently having trouble building phar.

https://github.com/box-project/box/issues/859

**Comment by DAcodedBEAT** [comment]
Ahh that makes sense, thanks for posting the underlying issue!

**Comment by jkowalleck** [comment]
0.8.6 was yanked from packagist.org and GitHub release list and git tags.

**Comment by icanhazstring** [comment]
Yep, sorry about that. But had to revert that. Because the whole build is kind of broken right now.
Still working on it.

**Comment by jkowalleck** [comment]
> Yep, sorry about that. But had to revert that. Because the whole build is kind of broken right now. Still working on it.

no worries, @icanhazstring .
Do whatever you think is best. Your work is appreciated.

**Comment by icanhazstring** [comment]
Hey guys. Managed to fix the phar build.
Rereleased 0.8.6.

The phar file is slightly bigger tho because I had to take some drawbacks :)
But hope it works for you.

Will close the issue now. If you still find issues please open a new one.

**Comment by datamweb** [comment]
@icanhazstring Thanks for your effort, it works fine now.
https://github.com/codeigniter4/shield/pull/660

**Comment by martin-1983** [comment]
@icanhazstring Thanks for taking care.

Unfortunately not all problems are solved yet. All GitHub releases (https://github.com/composer-unused/composer-unused/releases) since 0.8.3 are providing the PHAR file of version 0.8.2.

https://github.com/composer-unused/composer-unused/releases/download/0.8.1/composer-unused.phar => Version 0.8.1
https://github.com/composer-unused/composer-unused/releases/download/0.8.2/composer-unused.phar => Version 0.8.2
https://github.com/composer-unused/composer-unused/releases/download/0.8.3/composer-unused.phar => Version 0.8.2
https://github.com/composer-unused/composer-unused/releases/download/0.8.4/composer-unused.phar => Version 0.8.2
https://github.com/composer-unused/composer-unused/releases/download/0.8.5/composer-unused.phar => Version 0.8.2
https://github.com/composer-unused/composer-unused/releases/download/0.8.6/composer-unused.phar => Version 0.8.2

Would be great if this issue could also be fixed.

**Comment by icanhazstring** [comment]
Hi @martin-1983 . Thanks for reaching out.
That "version" the phar prints out is hardcoded in the command. 

I missed updating that on the releases. So that is why the version print is incorrect 😉

But the phar gets only build when a tag is created. So, you have the correct phar in these releases.
